[project]
name = "minstagram"
version = "0.1.0"
description = "Simple instagram clone project to learn FastAPI concepts fast"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.131.0",
    "python-dotenv>=1.2.1",
]
